# Hacer publicos los servicios desplegados

apiVersion: v1
kind: Service
metadata:
  name: nlb-service
spec:
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: api-gateway
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: register-service
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: crud-service
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: generics-front
  type: LoadBalancer
  selector:
    app: micros